const emergencyData = {
  trauma_centers: [
    { id: 'tc1', name: 'Apollo Hospital', lat: 13.0358, lng: 80.2464, phone: '+91-44-28293333', type: 'trauma', subtype: '24/7 Trauma Center', rating: 4.5, address: '21 Greams Lane, Off Greams Road, Chennai', beds: { icu: 12, emergency: 8 } },
    { id: 'tc2', name: 'MIOT International', lat: 13.0012, lng: 80.2378, phone: '+91-44-42002288', type: 'trauma', subtype: 'Multi-Specialty Hospital', rating: 4.4, address: '4/112, Mount Road, Chennai', beds: { icu: 8, emergency: 5 } },
    { id: 'tc3', name: 'Billroth Hospital', lat: 13.0550, lng: 80.2490, phone: '+91-44-42895555', type: 'trauma', subtype: 'Trauma Care', rating: 4.2, address: '43, Shenoy Nagar, Chennai', beds: { icu: 5, emergency: 10 } },
    { id: 'tc4', name: 'Fortis Malar', lat: 13.0475, lng: 80.2470, phone: '+91-44-42892222', type: 'trauma', subtype: 'Emergency & Trauma', rating: 4.3, address: '52, First Main Road, Gandhi Nagar, Adyar, Chennai', beds: { icu: 15, emergency: 12 } },
    { id: 'tc5', name: 'IIT Madras Hospital', lat: 12.9916, lng: 80.2336, phone: '+91-44-22578000', type: 'trauma', subtype: 'Campus Trauma Center', rating: 4.0, address: 'IIT Madras Campus, Chennai', beds: { icu: 4, emergency: 6 } }
  ],
  ambulances: [
    { id: 'amb1', name: '108 Emergency Services', lat: 13.0316, lng: 80.2204, phone: '108', type: 'ambulance', subtype: 'Emergency Ambulance', rating: 4.6, address: 'Control Room, Chennai' },
    { id: 'amb2', name: '102 Ambulance Service', lat: 13.0452, lng: 80.2420, phone: '102', type: 'ambulance', subtype: 'Government Ambulance', rating: 4.3, address: 'Govt. Hospital, Chennai' },
    { id: 'amb3', name: 'Red Cross Ambulance', lat: 13.0200, lng: 80.2350, phone: '+91-44-28411234', type: 'ambulance', subtype: '24/7 Service', rating: 4.4, address: 'Red Cross Building, Chennai' },
    { id: 'amb4', name: 'GVK Emergency Management', lat: 13.0600, lng: 80.2550, phone: '+91-44-24330555', type: 'ambulance', subtype: 'Critical Care Ambulance', rating: 4.5, address: 'GVK EMRI, Chennai' },
    { id: 'amb5', name: 'St. John Ambulance', lat: 13.0510, lng: 80.2300, phone: '+91-44-25393333', type: 'ambulance', subtype: 'First Response', rating: 4.1, address: 'St. John HQ, Chennai' }
  ],
  police_stations: [
    { id: 'ps1', name: 'Thoraipakkam Police Station', lat: 12.9870, lng: 80.2430, phone: '+91-44-24964999', type: 'police', subtype: 'Police Station', rating: 4.0, address: 'OMR Road, Thoraipakkam, Chennai' },
    { id: 'ps2', name: 'Guindy Police Station', lat: 13.0050, lng: 80.2200, phone: '+91-44-22354100', type: 'police', subtype: 'Police Station', rating: 4.1, address: 'Guindy, Chennai' },
    { id: 'ps3', name: 'Adyar Police Station', lat: 13.0020, lng: 80.2580, phone: '+91-44-24412666', type: 'police', subtype: 'Traffic & Law', rating: 4.2, address: 'Adyar, Chennai' },
    { id: 'ps4', name: 'Velachery Police Station', lat: 12.9780, lng: 80.2200, phone: '+91-44-22443111', type: 'police', subtype: 'Police Station', rating: 3.9, address: 'Velachery, Chennai' },
    { id: 'ps5', name: 'Saidapet Police Station', lat: 13.0280, lng: 80.2230, phone: '+91-44-24314771', type: 'police', subtype: 'Police Station', rating: 4.0, address: 'Saidapet, Chennai' }
  ],
  rescue: [
    { id: 'res1', name: 'Hyundai Roadside Assist', lat: 13.0350, lng: 80.2450, phone: '+91-1800-102-5000', type: 'rescue', subtype: 'Vehicle Rescue', rating: 4.3, address: 'Chennai Service Hub' },
    { id: 'res2', name: 'Maruti Suzuki Rescue', lat: 13.0250, lng: 80.2400, phone: '+91-1800-102-1800', type: 'rescue', subtype: '24/7 Towing', rating: 4.2, address: 'Chennai Central' },
    { id: 'res3', name: 'Aasra 24/7 Towing', lat: 12.9950, lng: 80.2150, phone: '+91-44-42890000', type: 'rescue', subtype: 'Towing Service', rating: 4.0, address: 'OMR Service Road' },
    { id: 'res4', name: 'City Tow Service', lat: 13.0400, lng: 80.2350, phone: '+91-44-42113333', type: 'rescue', subtype: 'Flatbed Towing', rating: 3.9, address: 'Anna Nagar, Chennai' },
    { id: 'res5', name: 'Highway Rescue', lat: 12.9800, lng: 80.2500, phone: '+91-44-23456789', type: 'rescue', subtype: 'Highway Assistance', rating: 4.0, address: 'OMR Highway' }
  ],
  emergency_contacts: [
    { id: 'ec1', name: 'National Emergency', phone: '112', type: 'contact', subtype: 'All-in-One Emergency', rating: 5.0 },
    { id: 'ec2', name: 'Ambulance', phone: '108', type: 'contact', subtype: 'Emergency Ambulance', rating: 5.0 },
    { id: 'ec3', name: 'Police', phone: '100', type: 'contact', subtype: 'Police Control Room', rating: 5.0 },
    { id: 'ec4', name: 'Fire Brigade', phone: '101', type: 'contact', subtype: 'Fire Emergency', rating: 5.0 },
    { id: 'ec5', name: 'Women Helpline', phone: '1091', type: 'contact', subtype: 'Women Emergency', rating: 5.0 }
  ],
  hazard_blackspots: [
    { id: 'bs1', lat: 13.0200, lng: 80.1950, name: 'Maduravoyal Junction', type: 'blackspot', severity: 'high', desc: 'Frequent accidents at this intersection' },
    { id: 'bs2', lat: 12.9900, lng: 80.1900, name: 'Porur Junction', type: 'blackspot', severity: 'high', desc: 'High-speed accidents common' },
    { id: 'bs3', lat: 12.9450, lng: 80.1940, name: 'Poonamallee High Road', type: 'blackspot', severity: 'medium', desc: 'Multiple accident history' },
    { id: 'bs4', lat: 13.0150, lng: 80.2280, name: 'Guindy Racetrack', type: 'blackspot', severity: 'medium', desc: 'Sharp curve accident zone' },
    { id: 'bs5', lat: 12.9700, lng: 80.2400, name: 'Thoraipakkam OMR', type: 'blackspot', severity: 'high', desc: 'High-speed road, frequent crashes' },
    { id: 'bs6', lat: 13.0450, lng: 80.2650, name: 'Thiruvanmiyur MRTS', type: 'blackspot', severity: 'medium', desc: 'Dense traffic accident zone' },
    { id: 'bs7', lat: 12.8770, lng: 80.0810, name: 'GST Road Singaperumal', type: 'blackspot', severity: 'high', desc: 'NH-45 highway accident hotspot' }
  ]
};

const translations = {
  en: {
    nav_home: 'Home',
    nav_services: 'Emergency Services',
    nav_report: 'Report Accident',
    nav_about: 'About',
    nav_contacts: 'Saved Contacts',
    nav_hazards: 'Hazard Map',
    hero_title: 'Road Safety Emergency Response',
    hero_subtitle: 'Instant help when you need it most',
    sos_button: 'SOS EMERGENCY',
    sos_sending: 'SENDING ALERT...',
    sos_sent: 'ALERT SENT! Help is on the way.',
    sos_confirm: '⚠️ Confirm Emergency',
    sos_cancel: 'Cancel',
    how_title: 'How It Works',
    how_step1: 'Tap SOS or select service',
    how_step2: 'We detect your location',
    how_step3: 'Nearest help reaches you',
    services_title: 'Nearby Emergency Services',
    search_placeholder: 'Search by area, pincode...',
    filter_all: 'All',
    filter_trauma: 'Trauma Centers',
    filter_ambulance: 'Ambulances',
    filter_police: 'Police',
    filter_rescue: 'Rescue',
    filter_contacts: 'Contacts',
    sort_distance: 'Distance',
    sort_rating: 'Rating',
    list_view: '📋 List',
    map_view: '🗺️ Map',
    call: 'Call',
    directions: 'Directions',
    share: 'Share',
    save: 'Save',
    km: 'km',
    no_services: 'No services found',
    report_title: 'Report an Accident',
    report_subtitle: 'Help us help you faster',
    report_location: '📍 Your Location',
    report_severity: '⚠️ Severity',
    report_minor: '🟢 Minor',
    report_moderate: '🟡 Moderate',
    report_severe: '🟠 Severe',
    report_critical: '🔴 Critical',
    report_photo: '📷 Upload Photo',
    report_desc: '📝 Description',
    report_desc_placeholder: 'Describe the accident...',
    report_submit: '🚨 Send Report to Emergency Services',
    report_sent: 'Report sent to emergency services!',
    about_title: 'About RoadSoS',
    about_desc: 'Built for the National Road Safety Hackathon 2026 organized by IIT Madras (CoERS). Our mission is to reduce emergency response time and save lives on Indian roads.',
    privacy: 'Your location data is used only during emergencies and never stored permanently.',
    hazards_title: '⚠️ Community Hazard Map',
    hazards_subtitle: 'Report & view road hazards — potholes, debris, broken signals, accident black spots',
    contacts_title: '💾 Saved Contacts',
    contacts_prompt: 'Tap the heart icon on any service to save it here for quick access.',
    lang_switch: 'हिन्दी',
    loading_location: 'Detecting your location...',
    location_error: 'Unable to detect location. Please enable GPS.',
    emergency_numbers: 'Emergency Helplines',
    nearest_services: 'Nearest Services',
    tap_sos: 'Tap the SOS button in an emergency',
    footer_text: '© 2026 RoadSoS — National Road Safety Hackathon, IIT Madras CoERS'
  },
  hi: {
    nav_home: 'होम',
    nav_services: 'आपातकालीन सेवाएं',
    nav_report: 'दुर्घटना रिपोर्ट',
    nav_about: 'हमारे बारे में',
    nav_contacts: 'सहेजे गए संपर्क',
    nav_hazards: 'खतरे का नक्शा',
    hero_title: 'सड़क सुरक्षा आपातकालीन प्रतिक्रिया',
    hero_subtitle: 'जरूरत पड़ने पर तुरंत मदद',
    sos_button: 'एसओएस आपातकालीन',
    sos_sending: 'अलर्ट भेज रहा है...',
    sos_sent: 'अलर्ट भेज दिया गया! मदद आ रही है।',
    sos_confirm: '⚠️ आपातकाल की पुष्टि करें',
    sos_cancel: 'रद्द करें',
    how_title: 'यह कैसे काम करता है',
    how_step1: 'SOS दबाएं या सेवा चुनें',
    how_step2: 'हम आपका स्थान पता करते हैं',
    how_step3: 'निकटतम मदद आप तक पहुँचती है',
    services_title: 'निकटतम आपातकालीन सेवाएं',
    search_placeholder: 'क्षेत्र, पिनकोड से खोजें...',
    filter_all: 'सभी',
    filter_trauma: 'ट्रॉमा सेंटर',
    filter_ambulance: 'एम्बुलेंस',
    filter_police: 'पुलिस',
    filter_rescue: 'बचाव',
    filter_contacts: 'संपर्क',
    sort_distance: 'दूरी',
    sort_rating: 'रेटिंग',
    list_view: '📋 सूची',
    map_view: '🗺️ मानचित्र',
    call: 'कॉल',
    directions: 'दिशा',
    share: 'शेयर',
    save: 'सहेजें',
    km: 'किमी',
    no_services: 'कोई सेवा नहीं मिली',
    report_title: 'दुर्घटना रिपोर्ट करें',
    report_subtitle: 'हमें आपकी तेज़ी से मदद करने दें',
    report_location: '📍 आपका स्थान',
    report_severity: '⚠️ गंभीरता',
    report_minor: '🟢 मामूली',
    report_moderate: '🟡 मध्यम',
    report_severe: '🟠 गंभीर',
    report_critical: '🔴 अत्यंत गंभीर',
    report_photo: '📷 फोटो अपलोड करें',
    report_desc: '📝 विवरण',
    report_desc_placeholder: 'दुर्घटना का वर्णन करें...',
    report_submit: '🚨 आपातकालीन सेवाओं को रिपोर्ट भेजें',
    report_sent: 'रिपोर्ट आपातकालीन सेवाओं को भेज दी गई!',
    about_title: 'RoadSoS के बारे में',
    about_desc: 'IIT Madras (CoERS) द्वारा आयोजित नेशनल रोड सेफ्टी हैकाथॉन 2026 के लिए बनाया गया। हमारा मिशन भारतीय सड़कों पर आपातकालीन प्रतिक्रिया समय कम करना और जीवन बचाना है।',
    privacy: 'आपका स्थान डेटा केवल आपातकाल के दौरान उपयोग किया जाता है और कभी स्थायी रूप से संग्रहीत नहीं किया जाता।',
    hazards_title: '⚠️ सामुदायिक खतरा मानचित्र',
    hazards_subtitle: 'सड़क खतरों की रिपोर्ट करें और देखें — गड्ढे, मलबा, टूटे सिग्नल, दुर्घटना ब्लैक स्पॉट',
    contacts_title: '💾 सहेजे गए संपर्क',
    contacts_prompt: 'त्वरित पहुंच के लिए किसी भी सेवा पर हृदय आइकन टैप करें।',
    lang_switch: 'English',
    loading_location: 'आपका स्थान पता कर रहा है...',
    location_error: 'स्थान का पता नहीं लगाया जा सका। कृपया GPS चालू करें।',
    emergency_numbers: 'आपातकालीन हेल्पलाइन',
    nearest_services: 'निकटतम सेवाएं',
    tap_sos: 'आपातकाल में SOS बटन दबाएं',
    footer_text: '© 2026 RoadSoS — नेशनल रोड सेफ्टी हैकाथॉन, IIT Madras CoERS'
  }
};
